resources:
  repositories:
    - repository: CIP
      type: GitHub
      endpoint: pwc-us-adv-cloud-intelligence-ccs-signal-qualification-service
      name: vijayakumary01/Test04
      trigger:
        branches:
          include:
          - '*'  # must quote since "*" is a YAML reserved character; we want a string
      pr:
      - develop



trigger: none


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'