#resources:
  #repositories:
    #- repository: Anyname
      #type: GitHub
      #endpoint: github.com_vijayakumary01
      #name: vijayakumary01/Test04
      #trigger:
        #branches:
          #include:
          #- '*'  # must quote since "*" is a YAML reserved character; we want a string
      #pr:
        #branches:
          #include:
           #- develop


resources:
  webhooks:
    - webhook: ICWebHook          
      connection: ICWebHook    
      filters:
        - path: repositoryName      
          value: vijayakumary01/Test03     
        - path: action
          value: CREATED




pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'